### PR TITLE
Added my Python program

### PR DESCRIPTION
**Pull request by 2002-ishaan**
My Hacktoberfest Contribution

### CODE REVIEW

**Review by srinidh-007 — CHANGES_REQUESTED** [review]
Add documentation

**Comment by srinidh-007** [comment]
Keep a proper file name

**Comment by 2002-ishaan** [comment]
I have changed the file name as suggested. I am new to open source, please tell me what add documentation means?

**Comment by srinidh-007** [comment]
write proper comments explaining what your code will do and add a  first top comment explaining the problem statement

**Comment by 2002-ishaan** [comment]
Okay got it, thanks!

**Review by srinidh-007 — APPROVED** [review]

**Pull request merged**
